# Use root/example as user/password credentials
version: '3.1'

services:

  lawManagerDB:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'dev'
      MONGO_INITDB_ROOT_PASSWORD: 'dev_password'
    ports: 
    - 27017:27017